### ISSUE TITLE
rd_kafka_rebalance_protocol() can hang when called from rebalance callback after consumer close

### ISSUE THREAD

**Issue by jdemeyer** [confluentinc/confluent-kafka-go#1016]
Description
===========

In rare cases, it can happen that the consumer `Close()` hangs forever. The stack trace points to `rd_kafka_rebalance_protocol`. So this sounds very related to https://github.com/confluentinc/librdkafka/issues/4041

The relevant part of the stacktrace:
```
goroutine 83 [syscall, 9 minutes]:
github.com/confluentinc/confluent-kafka-go/v2/kafka._Cfunc_rd_kafka_rebalance_protocol(0x7f817c001890)
        _cgo_gotypes.go:3749 +0x4d
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).GetRebalanceProtocol.func1(0xc007a41698?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.1.1/kafka/consumer.go:224 +0x46
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).GetRebalanceProtocol(0xc001300000?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.1.1/kafka/consumer.go:224 +0x19
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).handleRebalanceEvent(0xc007874fc0, 0x0, 0xc0012e14a0?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.1.1/kafka/consumer.go:1042 +0xeb
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*handle).eventPoll(0xc007874fc8, 0x0, 0x0, 0xc0012e1778?, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.1.1/kafka/event.go:182 +0x609
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Poll(...)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.1.1/kafka/consumer.go:450
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Close(0x95d502?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.1.1/kafka/consumer.go:545 +0xed
```

How to reproduce
================

It's a race condition which happens only rarely. So far, I have not attempted to make a reproducer.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): confluent-kafka-go 2.1.1 with bundled librdkafka 2.1.1
 - [x] Apache Kafka broker version: librdkafka mock cluster
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: GNU/Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jdemeyer** [comment]
I've also seen a different hang during `Close()`:
```
goroutine 79 [syscall, 9 minutes]:
github.com/confluentinc/confluent-kafka-go/v2/kafka._Cfunc_rd_kafka_assign(0x7fbd42921740, 0x0)
        _cgo_gotypes.go:2780 +0x4b
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).handleRebalanceEvent.func5(0x7fbd41eb2a80?)
        /go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.2.0/kafka/consumer.go:1065 +0x46
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).handleRebalanceEvent(0xc0013603c0, 0x0, 0x0?)
        /go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.2.0/kafka/consumer.go:1065 +0x177
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*handle).eventPoll(0xc0013603c8, 0x0, 0x0, 0xc0000f7758?, 0x0)
        /go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.2.0/kafka/event.go:182 +0x669
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Poll(...)
        /go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.2.0/kafka/consumer.go:450
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Close(0x960ebf?)
        /go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.2.0/kafka/consumer.go:545 +0xe5
```

**Comment by jdemeyer** [comment]
Both issues still reproduce with 2.3.0:
```
goroutine 80 [syscall, 8 minutes]:
github.com/confluentinc/confluent-kafka-go/v2/kafka._Cfunc_rd_kafka_rebalance_protocol(0x7efe6c005a90)
        _cgo_gotypes.go:4727 +0x48
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).GetRebalanceProtocol.func1(0xc004a4a270?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:225 +0x3d
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).GetRebalanceProtocol(0xc000100000?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:225 +0x13
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).handleRebalanceEvent(0xc00313e0d0, 0x0, 0xc004e8bd40?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:1053 +0xd3
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*handle).eventPoll(0xc00313e0d8, 0x0, 0x0, 0x473905?, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/event.go:182 +0x669
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Poll(...)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:451
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Close(0xc00313e0d0)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:553 +0x156
```
and
```
goroutine 91 [syscall, 8 minutes]:
github.com/confluentinc/confluent-kafka-go/v2/kafka._Cfunc_rd_kafka_assign(0x7f091c0145a0, 0x0)
        _cgo_gotypes.go:3299 +0x4b
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).handleRebalanceEvent.func5(0x7f092c013270?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:1076 +0x46
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).handleRebalanceEvent(0xc004481d40, 0x0, 0xc002d26480?)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:1076 +0x177
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*handle).eventPoll(0xc004481d48, 0x0, 0x0, 0x473905?, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/event.go:182 +0x669
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Poll(...)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:451
github.com/confluentinc/confluent-kafka-go/v2/kafka.(*Consumer).Close(0xc004481d40)
        /home/jdemeyer/go/pkg/mod/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka/consumer.go:553 +0x156
```

**Comment by Millione** [comment]
Any progress here？
