### ISSUE TITLE
[Q] Best way of re-reading messages

### ISSUE THREAD

**Issue by MrDHat** [confluentinc/confluent-kafka-go#134]
Description
===========
I have some messages being produced which are essentially scheduling tasks, so I want to read them, check if they should be processed now, if not process them later. How should I go about getting this functionality?

I am setting `enable.auto.commit` to `false` so that I can read again later (and commit them at that time).I am not sure how to re-read the messages from the same instance of the consumer. If it is of any help I am using channel based consumer to consume the messages.

**Comment by edenhill** [comment]
You can use Seek() to change the fetch position of an active consumer.
If you want to set the start offset you can pass an offset per TopicPartition in the call to Assign().

More info: https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset

**Comment by MrDHat** [comment]
Thanks for the quick answer @edenhill!

I tried using `Seek` but I am getting a panic. Here is what the code looks like:

```go
var runningOffsets []kafka.TopicPartition

	run := true
	for run == true {
		select {
		case sig := <-sigchan:
			log.Println(sig)
			run = false
		case ev := <-Consumer.Events():
			log.Println("ev", ev)
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				log.Println("kafka.AssignedPartitions", e)
				Consumer.Assign(e.Partitions)
			case kafka.RevokedPartitions:
				log.Println("kafka.RevokedPartitions", e)
				Consumer.Unassign()
			case *kafka.Message:
				runningOffsets = append(runningOffsets, e.TopicPartition)
				log.Println(e.TopicPartition, e.Value, e.Key, e.Timestamp, e.TimestampType)
				log.Println(e)
				
				log.Println("running", runningOffsets)
			case kafka.PartitionEOF:
				log.Println(e)
				// Get the lowest offset and seek to that position
				var lowestOffset kafka.Offset = math.MaxInt64
				var lowestPartition kafka.TopicPartition
				if len(runningOffsets) > 0 {
					for _, e := range runningOffsets {
						if e.Offset < lowestOffset {
							lowestOffset = e.Offset
							lowestPartition = e
						}
					}
					if lowestOffset != math.MaxInt64 {
						log.Println("SEEKING...", lowestPartition, lowestOffset)
						err := Consumer.Seek(lowestPartition, 0)
						if err != nil {
							runningOffsets = []kafka.TopicPartition{}
						} else {
							log.Println(err)
						}
					}
				}
			case kafka.Error:
				log.Println(e)
				run = false
			}

		}
	}
```

The code creates a slice to store all the ongoing offsets, then "seeks" back to the first seen offset once EoF is received. I am getting a panic when `Seek` is called. Here is the stacktrace:

```
2018/02/19 10:39:24 SEEKING... kron-schedule-test[0]@0 0
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f3b9dfc1b20]

runtime stack:
runtime.throw(0x713b5c, 0x2a)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x669e50, 0xc4200f58f0, 0x100)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc4200f58a8 sp=0xc4200f5868 pc=0x405784
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_rd_kafka_seek(0x7f3b90001710, 0x7f3b00000000, 0x0, 0x0, 0x0)
	github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/_obj/_cgo_gotypes.go:1036 +0x4d fp=0xc4200f58f0 sp=0xc4200f58a8 pc=0x4de93d
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Consumer).Seek.func1(0x7f3b90001710, 0xc400000000, 0x0, 0x7f3b00000000, 0xc4201b6810)
	/go/src/github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:238 +0x7a fp=0xc4200f5928 sp=0xc4200f58f0 pc=0x4e57ba
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Consumer).Seek(0xc4200ec000, 0xc420011010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x43, 0x7f3b9e68d008)
	/go/src/github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:238 +0x77 fp=0xc4200f5978 sp=0xc4200f5928 pc=0x4e0d07
github.com/getstrike/kron/kron.(*Kron).Start(0xc4200f5ec0, 0x18, 0xc4200160d9)
	/go/src/github.com/getstrike/kron/kron/kron.go:225 +0x1066 fp=0xc4200f5e38 sp=0xc4200f5978 pc=0x668b06
main.main()
	/go/src/github.com/getstrike/kron/examples/example.go:13 +0x61c fp=0xc4200f5f80 sp=0xc4200f5e38 pc=0x66960c
runtime.main()
	/usr/local/go/src/runtime/proc.go:195 +0x226 fp=0xc4200f5fe0 sp=0xc4200f5f80 pc=0x42f5a6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200f5fe8 sp=0xc4200f5fe0 pc=0x45be91

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [syscall, locked to thread]:
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka._Cfunc__rk_queue_poll(0x1061720, 0x64, 0xc4201bed5c, 0xc4201bbf80, 0x0, 0x0)
	github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/_obj/_cgo_gotypes.go:437 +0x4e
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*handle).eventPoll.func1(0x1061720, 0xc400000064, 0xc4201bed5c, 0xc4201bbf80, 0x0, 0x0)
	/go/src/github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/event.go:156 +0x138
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*handle).eventPoll(0xc4200ec008, 0xc4200542a0, 0x64, 0x3e8, 0xc42001e180, 0x0, 0x0, 0x0)
	/go/src/github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/event.go:156 +0x16b
github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka.consumerReader(0xc4200ec000, 0xc42001e180)
	/go/src/github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:459 +0x77
created by github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer
	/go/src/github.com/getstrike/kron/kron/vendor/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:430 +0x569

goroutine 7 [select, locked to thread]:
runtime.gopark(0x71db60, 0x0, 0x707f64, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc42003ef50, 0xc42001e240)
	/usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x7f3b9e62cf70, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200ea518, 0x72, 0xffffffffffffff00, 0xa6afa0, 0xa67a98)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200ea518, 0xc420295000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200ea500, 0xc420295000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc4200ea500, 0xc420295000, 0x1000, 0x1000, 0x42fbab, 0xc420038a40, 0x457f40)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e0e8, 0xc420295000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc420078c60, 0xc420295000, 0x1000, 0x1000, 0xc4200189b0, 0xc42001e8f8, 0x4562d0)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc420054c60)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc420054c60, 0x1, 0x0, 0x0, 0x0, 0xc4201695c0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc420078c60)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc420078c60)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53
exit status 2
```

**Comment by edenhill** [comment]
What version of the Go client and librdkafka?

**Comment by MrDHat** [comment]
Both from the tip of the master branch

**Comment by edenhill** [comment]
Reproduced the issue, it is a bug in librdkafka when seek() is called with a timeout of 0.
I'll push a fix, in the meantime use timeout=1 as a workaround

**Comment by MrDHat** [comment]
Oh great! Thanks!

What is best practice for the timeout btw? Do you see a lot of people using `0`?

**Comment by edenhill** [comment]
Having a timeout on the seek() API was a mistake, it is a completely local operation and is immediate.

So an infinite timeout is okay to use.
