### ISSUE TITLE
SIGSEGV during consumer Close

### ISSUE THREAD

**Issue by binary132** [confluentinc/confluent-kafka-go#136]
Description
===========

SIGSEGV during consumer Close:

```
fatal error: unexpected signal during runtime execution                                                                      [17/155]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b2943c]

runtime stack:
runtime.throw(0x46252d3, 0x2a)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x44ef940, 0xc4201653f0, 0x4624876)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/cgocall.go:132 +0xe4 fp=0xc4201653b0 sp=0xc420165370 pc=0x4003c24
gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka._Cfunc__rk_queue_poll(0x0, 0x1388, 0xc420017368, 0xc4
200efe00, 0x0, 0x0)
        gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka/_obj/_cgo_gotypes.go:415 +0x4e fp=0xc4201653f
0 sp=0xc4201653b0 pc=0x4345afe
gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*handle).eventPoll.func1(0x0, 0xc400001388, 0xc42001
7368, 0xc4200efe00, 0x0, 0x0)
        /Users/jsolomon/meta/current/fw-go/src/gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka/event.
go:122 +0x138 fp=0xc420165438 sp=0xc4201653f0 pc=0x4353748
gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*handle).eventPoll(0xc4201ab7a8, 0x0, 0x1388, 0x1, 0
x0, 0x0, 0x0, 0x0)
        /Users/jsolomon/meta/current/fw-go/src/gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka/event.
go:122 +0x16b fp=0xc420165808 sp=0xc420165438 pc=0x434cf4b
gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Consumer).Poll(0xc4201ab7a0, 0x1388, 0x23, 0x0)
        /Users/jsolomon/meta/current/fw-go/src/gorpt/message/confluent/vendor/github.com/confluentinc/confluent-kafka-go/kafka/consum
er.go:255 +0x56 fp=0xc420165858 sp=0xc420165808 pc=0x434b266
gorpt/message/confluent.(*Confluent).Listen(0xc420065e40, 0x46338c0, 0xc42007e360)
        /Users/jsolomon/meta/current/fw-go/src/gorpt/message/confluent/confluent.go:149 +0x125 fp=0xc420165bd0 sp=0xc420165858 pc=0x4
357975

# ...

goroutine 5 [syscall]:
os/signal.signal_recv(0x4905c60)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/sigqueue.go:131 +0xa7
os/signal.loop()
        /usr/local/Cellar/go/1.9.4/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/Cellar/go/1.9.4/libexec/src/os/signal/signal_unix.go:28 +0x41
```

How to reproduce
================

Called `Close` on kafka.Consumer while Listen was running in another goroutine.

Still investigating.  It appears to be a NULL dereference in `librdkafka`: 

>```
>[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b2943c]
>                                                       ^ NULL addr 
>```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 26450c3
 - [x] Apache Kafka broker version: (I think 0.10?)
  - [x] Client configuration: `ConfigMap{...}`
- [x] Operating system: OS X 10.13
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by binary132** [comment]
Here are the "debug: all" client logs at the point of termination:

```
%7|1518815555.971|TERMINATE|rdkafka#consumer-1| [thrd:main]: Main background thread exiting
%7|1518815555.971|TERMINATE|rdkafka#consumer-1| [thrd:app]: Destroying op queues
%7|1518815555.971|TERMINATE|rdkafka#consumer-1| [thrd:app]: Destroying cgrp
%7|1518815555.971|MEMBERID|rdkafka#consumer-1| [thrd:app]: Group "nbcu-fw-proto": updating member id "" -> "(not-set)"
%7|1518815555.971|TERMINATE|rdkafka#consumer-1| [thrd:app]: Termination done: freeing resources
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a5143c]
```

**Comment by binary132** [comment]
Config:

```go
&kafka.ConfigMap{
	"bootstrap.servers":  conf.Brokers,
	"group.id":           conf.Group,
	"client.id":          conf.ClientID,
	"session.timeout.ms": 120000,
	"enable.auto.commit": false,
	"default.topic.config": kafka.ConfigMap{
		"auto.offset.reset": "latest",
	},
	"debug": "all",
})
```

**Comment by binary132** [comment]
I'm also getting some logs like:

```
%7|1518815531.201|CONNECT|rdkafka#consumer-1| [thrd:ip-WW-XX-YY-ZZ.ec2.internal:9092/4]: ip-WW-XX-YY-ZZ.ec2.internal:9092/4: broker in state DOWN connecting                                                                                                            
%7|1518815531.204|BROKERFAIL|rdkafka#consumer-1| [thrd:ip-WW-XX-YY-ZZ.ec2.internal:9092/4]: ip-WW-XX-YY-ZZ.ec2.internal:9092/4: failed: err: Local: Host resolution failure: (errno: Bad address)                                                                       
%
```

So perhaps the failure is happening because Close can't call the backend?

**Comment by edenhill** [comment]
Is this reproducible with the consumer_example?

**Comment by wadinj** [comment]
Hi, 

I think this still a relevant issue. I got exactly the same. 
```
	consumer, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":     cfg.Broker.BootstrapServers,
		"group.id":              cfg.Broker.GroupId,
		"auto.offset.reset":     "earliest",
		"broker.address.family": "v4",
	})
        err = consumer.SubscribeTopics([]string{cfg.Broker.PollerTopicName}, nil)
       env.Consumer = consumer
        go func() { 
              ev := env.Consumer.Poll(10)
       }()
     // do anything to never stop 
```

And handle Interrupt signal with:
```
signal.Notify(shutdownSignal, os.Interrupt,syscall.SIGINT, syscall.SIGTERM, syscall.SIGSEGV)

	go func(env *env.Environment) {
		sigReceived := <-shutdownSignal
                env.Consumer.Close()
       }
```

Throw a SIGSEGV

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x571fe08]

runtime stack:
runtime.throw(0x49fcf7c, 0x2a)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/signal_unix.go:378 +0x47c

goroutine 132 [syscall]:
runtime.cgocall(0x4807160, 0xc001d60580, 0xc0004f80c0)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc001d60550 sp=0xc001d60518 pc=0x40050cb
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka._Cfunc__rk_queue_poll(0x0, 0xa, 0xc00051c04c, 0xc0004f80c0, 0x0, 0x0)
	_cgo_gotypes.go:569 +0x4e fp=0xc001d60580 sp=0xc001d60550 pc=0x45af95e
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*handle).eventPoll.func1(0xc0000b41b8, 0xc001d608c0, 0xc00051c04c, 0xc0004f80c0, 0xc001d606a8, 0x0)
	/Users/jonathanwadin/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.1.0/kafka/event.go:168 +0x141 fp=0xc001d605d8 sp=0xc001d60580 pc=0x45c12c1
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*handle).eventPoll(0xc0000b41b8, 0x0, 0xa, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/jonathanwadin/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.1.0/kafka/event.go:168 +0x122 fp=0xc001d608b0 sp=0xc001d605d8 pc=0x45b76c2
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*Consumer).Poll(...)
```

**Comment by edenhill** [comment]
I think the problem is that you're not terminating the consumer poll go-routine prior to closing the consumer, which means the closed consumer will be accessed after destruction.

**Comment by wadinj** [comment]
Hi @edenhill ,

Nice hint ! That was exactly the case. I just properly propagate a channel from the go-routine to stop the polling before the consumer and the SIGSEGV is gone !

Thanks for the hint !
