### ISSUE TITLE
Producer produce function causes a runtime error during cgo check (cgo argument has Go pointer to Go pointer )

### ISSUE THREAD

**Issue by nidhog** [confluentinc/confluent-kafka-go#159]
> Issue details:
>  - go version go1.9.2 darwin/amd64
>  - Library version: *721151 0.11.0*
>  - Apache Kafka broker version *2.11-0.11.0.1*
>  - Mac OS X, version 10.12.5
> 

Description
===========
We get a runtime error if the producer's message contains fewer than 64 bytes. The program exits with the output :
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 35 [running]:
kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).produce.func1(0x5005800, 0x4b01930, 0x6ffffffff, 0xc4218be028, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:128 +0xc0
kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).produce(0xc420102000, 0xc4218b4090, 0x4, 0x0, 0x0, 0x0)
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:128 +0x29b
kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.channelProducer(0xc420102000)
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:309 +0x97
created by kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.NewProducer
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:299 +0x567
exit status 2
```
This only happens in our case if: 

-  the message is defined directly using `buffer.Bytes()` where `buffer` is a `bytes.Buffer` struct.
-  the message contains fewer than 64 bytes.

How to reproduce
================
In the following example, we reproduce the previous error by creating a go server. The go server receives a request and tries to produce a message to the Kafka broker. The server will handle three  `POST` requests to verify the assumptions in the previous section:

- A request that results in producing a message containing less than 64 bytes and using `buffer.Bytes()`. This request should cause the program to exit with status code 2.
- A request that results in producing a message containing less than 64 bytes but using a copy of `buffer.Bytes()` into a byte slice with preallocated memory. This request should succeed.
- A request that results in producing a message containing less than 64 bytes and using `buffer.Bytes()`. This request should succeed.

To reproduce the error, make sure that the Kafka broker is running on port _9092_ and that nothing is running on port _8000_ as we will use the latter for listening to incoming requests.

Create a new go file `producer_server.go` containing the following:
```go
package main

import (
	"fmt"
	"github.com/gorilla/mux"
	"kafkaproducer-api/producer"
	"net/http"
	"os"
	"bytes"
	"encoding/json"
	"github.com/confluentinc/confluent-kafka-go/kafka"
)


type kafkaProducerHandler struct {
	producer producer.Producer
}

type Message struct {
	Value string `json:"value"`
}

func main() {
	fmt.Println(kafka.LibraryVersion())
	serverPort := "8000"
	brokerAddress := "localhost:9092"
	router := mux.NewRouter().PathPrefix("/kafka").Subrouter()
	kafkaProducer, err := producer.NewKafkaProducer(brokerAddress)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	handler := kafkaProducerHandler{producer:kafkaProducer}

	// send a message shorter than 64 bytes directly using b.bytes(), this should fail
	router.HandleFunc("/fail-short", handler.produceMessageShortFail).Methods("POST")
	// send a message shorter than 64 bytes which is a copy with pre-allocated memory, this should succeed
	router.HandleFunc("/success-short", handler.produceMessageShortSuccess).Methods("POST")
	// send a message longer than 64 bytes directly using b.bytes(), this should succeed
	router.HandleFunc("/success-long", handler.produceMessageLongSuccess).Methods("POST")

	if err := http.ListenAndServe(fmt.Sprintf(":%v", serverPort), router); err != nil {
		fmt.Printf("%v", err)
	}
}

func (handler *kafkaProducerHandler) produceMessageShortFail(w http.ResponseWriter, r *http.Request) {
	message := Message{"Hello, world"}
	fmt.Println("Using Producer Message with less than 64 bytes:", message)

	buffer := new(bytes.Buffer)
	json.NewEncoder(buffer).Encode(message)
	fmt.Println("Message length:", buffer.Len())

	producerMessage := buffer.Bytes()

	fmt.Println("Producing message:", string(producerMessage))
	handler.producer.Produce(producerMessage, "test")
}

func (handler *kafkaProducerHandler) produceMessageShortSuccess(w http.ResponseWriter, r *http.Request) {
	message := Message{"Hello, world"}
	fmt.Println("Using Producer Message with less than 64 bytes:", message)

	buffer := new(bytes.Buffer)
	json.NewEncoder(buffer).Encode(message)
	fmt.Println("Message length:", buffer.Len())

	// create a copy of the slice
	producerMessage := buffer.Bytes()
	messageClone := make([]byte, buffer.Len())
	copy(messageClone, producerMessage)

	fmt.Println("Producing message using a copy:", string(messageClone))
	handler.producer.Produce(messageClone, "test")
}

func (handler *kafkaProducerHandler) produceMessageLongSuccess(w http.ResponseWriter, r *http.Request) {
	message := Message{"This Message is larger than 64 bytes" +
		".........................................................."}
	fmt.Println("Using Producer Message with more than 64 bytes", message)

	buffer := new(bytes.Buffer)
	json.NewEncoder(buffer).Encode(message)
	fmt.Println("Message length:", buffer.Len())

	producerMessage := buffer.Bytes()

	fmt.Println("Producing message:", string(producerMessage))
	handler.producer.Produce(producerMessage, "test")
}
```
To start the server run:
```bash
go run producer_server.go
```
In order to reproduce the error, produce a message with less than 64 bytes that will cause the server to fail, send a `POST` request to the endpoint `http://localhost:8000/kafka/fail-short`. This should fail.

```bash
curl -X POST http://localhost:8000/kafka/fail-short -v
```
To verify that the latter works in case the message's length is larger than 64 bytes, send a `POST` request to the endpoint `http://localhost:8000/kafka/success-long`. This should succeed.

```bash
curl -X POST http://localhost:8000/kafka/success-long -v
```
To verify that the producer succeeds in case we copy the byte array beforehand, send a `POST` request to the endpoint `http://localhost:8000/kafka/success-short`. This should succeed.
```bash
curl -X POST http://localhost:8000/kafka/success-short -v
```

This should exit giving the following output:
```
Using Producer Message: {Hello, world}
Message length: 25
Producing message: {"value":"Hello, world"}

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 35 [running]:
kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).produce.func1(0x5005800, 0x4b01930, 0x6ffffffff, 0xc4218be028, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:128 +0xc0
kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).produce(0xc420102000, 0xc4218b4090, 0x4, 0x0, 0x0, 0x0)
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:128 +0x29b
kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.channelProducer(0xc420102000)
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:309 +0x97
created by kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka.NewProducer
	/Users/username/go/src/kafkaproducer-api/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:299 +0x567
exit status 2
```

**Comment by edenhill** [comment]
nit: "kafkaproducer-api/producer" seems to be your internal package.

I tried to reproduce this by altering the producer_example.go to:
```
	buffer := new(bytes.Buffer)
	buffer.WriteString("\"Hello, world\"")

	err = p.Produce(&kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
		Value:          buffer.Bytes(),
		Headers:        []kafka.Header{{"myTestHeader", []byte("header values are binary")}},
	}, deliveryChan)
```

But it works just fine on v0.11.4.

Did you try v0.11.4?

**Comment by nidhog** [comment]
Thanks for the reply!
Right, I completely missed that detail `kafkaproducer-api/producer` contains a `Producer` interface that we defined internally.  
Tried using v0.11.4 but it fails as well.
We are however using `ProduceChannel` instead of `Produce`, hence the go routine . Here's what it looks like :
```
Producer interface, allowing for easy mocking in unit tests
type Producer interface {
	CreateProducer() error
	Produce(event []byte, topic string)
	GetMetadata(timeout int) (*kafka.Metadata, error)
	Teardown()
}

func (kp *KafkaProducer) Produce(event []byte, topic string) {
	kp.producer.ProduceChannel() <- &kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
		Value:          event,
	}
}
```
