### ISSUE TITLE
siem-log-agent: rdkafka_broker.c:4773: rd_kafka_broker_add_logical: Assertion `rkb && *"failed to create broker thread"' failed.

### ISSUE THREAD

**Issue by thangld322** [confluentinc/confluent-kafka-go#342]
Hi,
I'm building a logs shipper with Go to send logs from kafka to elasticsearch. It works well on ubuntu 18.04.2. But when I copy the binary file to a debian docker container and run it, it returns this error: 
Description
===========

```
%2|1561006220.303|THREAD|rdkafka#consumer-1| [thrd:app]: Unable to create broker thread: Invalid argument (22)
siem-log-agent: rdkafka_broker.c:4773: rd_kafka_broker_add_logical: Assertion `rkb && *"failed to create broker thread"' failed.
SIGABRT: abort
PC=0x7f397ea6a7bb m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f397ea6a7bb
stack: frame={sp:0x7fff2540d860, fp:0x0} stack=[0x7fff24c0ee28,0x7fff2540de50)
00007fff2540d760:  0000000000000000  00007f397ea3aa88 
00007fff2540d770:  00007fff2540db10  00007f397ef684ba 
00007fff2540d780:  0000000000000000  00007f397ecd7570 
00007fff2540d790:  0000000000000064  0000000000000002 
00007fff2540d7a0:  0000000000000007  0000000000000070 
00007fff2540d7b0:  0000000000000007  0000000001e3d038 
00007fff2540d7c0:  000000000000005f  0000000000000090 
00007fff2540d7d0:  ffffffffffffe1c8  0000000000000001 
00007fff2540d7e0:  0000003100000007  0000000000000000 
00007fff2540d7f0:  0000000000000000  0000006e0000005b 
00007fff2540d800:  000000770000007c  0000000000000000 
00007fff2540d810:  ffffffffffffffff  00007f397ebeec40 
00007fff2540d820:  0000000000000064  0000000000000005 
00007fff2540d830:  33373734ffffe1c8  1aae49a8db291e00 
00007fff2540d840:  00007fff2540d880  0000000000000081 
00007fff2540d850:  0000000000000081  00007fff2540dac0 
00007fff2540d860: <0000000000000000  0000000001e40e60 
00007fff2540d870:  0000000001e40630  00007f397eaab4d7 
00007fff2540d880:  00000000fbad8000  0000000001e40e60 
00007fff2540d890:  0000000001e40ec5  0000000001e40e60 
00007fff2540d8a0:  0000000001e40e60  0000000001e40ee1 
00007fff2540d8b0:  0000000001e40f8c  0000000001e40e60 
00007fff2540d8c0:  0000000001e40f8c  0000000000000000 
00007fff2540d8d0:  0000000000000000  0000000000000000 
00007fff2540d8e0:  fffffffe7fffffff  ffffffffffffffff 
00007fff2540d8f0:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d900:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d910:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d920:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d930:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d940:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d950:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f397ea6a7bb
stack: frame={sp:0x7fff2540d860, fp:0x0} stack=[0x7fff24c0ee28,0x7fff2540de50)
00007fff2540d760:  0000000000000000  00007f397ea3aa88 
00007fff2540d770:  00007fff2540db10  00007f397ef684ba 
00007fff2540d780:  0000000000000000  00007f397ecd7570 
00007fff2540d790:  0000000000000064  0000000000000002 
00007fff2540d7a0:  0000000000000007  0000000000000070 
00007fff2540d7b0:  0000000000000007  0000000001e3d038 
00007fff2540d7c0:  000000000000005f  0000000000000090 
00007fff2540d7d0:  ffffffffffffe1c8  0000000000000001 
00007fff2540d7e0:  0000003100000007  0000000000000000 
00007fff2540d7f0:  0000000000000000  0000006e0000005b 
00007fff2540d800:  000000770000007c  0000000000000000 
00007fff2540d810:  ffffffffffffffff  00007f397ebeec40 
00007fff2540d820:  0000000000000064  0000000000000005 
00007fff2540d830:  33373734ffffe1c8  1aae49a8db291e00 
00007fff2540d840:  00007fff2540d880  0000000000000081 
00007fff2540d850:  0000000000000081  00007fff2540dac0 
00007fff2540d860: <0000000000000000  0000000001e40e60 
00007fff2540d870:  0000000001e40630  00007f397eaab4d7 
00007fff2540d880:  00000000fbad8000  0000000001e40e60 
00007fff2540d890:  0000000001e40ec5  0000000001e40e60 
00007fff2540d8a0:  0000000001e40e60  0000000001e40ee1 
00007fff2540d8b0:  0000000001e40f8c  0000000001e40e60 
00007fff2540d8c0:  0000000001e40f8c  0000000000000000 
00007fff2540d8d0:  0000000000000000  0000000000000000 
00007fff2540d8e0:  fffffffe7fffffff  ffffffffffffffff 
00007fff2540d8f0:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d900:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d910:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d920:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d930:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d940:  ffffffffffffffff  ffffffffffffffff 
00007fff2540d950:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x9f9fd0, 0xc000189a60, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000189a30 sp=0xc0001899f8 pc=0x40938b
github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_rd_kafka_new(0x1, 0x1e3d820, 0x1e3e2c0, 0x100, 0x0)
	_cgo_gotypes.go:1683 +0x4e fp=0xc000189a60 sp=0xc000189a30 pc=0x9e497e
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer.func3(0x1e3d820, 0x1e3e2c0, 0x0)
	/home/thangld13/go/src/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:414 +0x71 fp=0xc000189a98 sp=0xc000189a60 pc=0x9f1c41
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer(0xc000189bb0, 0x0, 0x0, 0x0)
	/home/thangld13/go/src/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:414 +0x2b3 fp=0xc000189b40 sp=0xc000189a98 pc=0x9e92f3
siem-log-agent/input/rdkafkainput.InitHandler(0xc621e0, 0xc00019a400, 0xb82887, 0x5, 0xc0001ba498, 0xc0001a0f01)
	/home/thangld13/go/src/siem-log-agent/input/rdkafkainput/kafkainput.go:61 +0x20c fp=0xc000189ca8 sp=0xc000189b40 pc=0x9f774c
siem-log-agent/config.(*Config).getInputs(0xc00019e0f0, 0xc000198cc0, 0xc000189d50, 0xc000189d50, 0x412378, 0x30)
	/home/thangld13/go/src/siem-log-agent/config/input.go:50 +0x80 fp=0xc000189d08 sp=0xc000189ca8 pc=0x9e0cd0
siem-log-agent/config.(*Config).startInputs(0xc00019e0f0, 0xc0001a0f00, 0xc621e0)
	/home/thangld13/go/src/siem-log-agent/config/input.go:26 +0x2f fp=0xc000189d60 sp=0xc000189d08 pc=0x9e0baf
siem-log-agent/config.(*Config).Start(0xc00019e0f0, 0xc62220, 0xc0000ca010, 0x1, 0x1)
	/home/thangld13/go/src/siem-log-agent/config/config.go:47 +0x1c0 fp=0xc000189e50 sp=0xc000189d60 pc=0x9e08b0
siem-log-agent/agent.(*CyMLogAgent).launch(0xc000189ee0, 0x0, 0xc0001b62a0)
	/home/thangld13/go/src/siem-log-agent/agent/agent.go:47 +0x15b fp=0xc000189ec8 sp=0xc000189e50 pc=0x9f808b
siem-log-agent/agent.Run(0xb85169, 0xc, 0xb8261b, 0x5, 0xc0001ac5dc, 0x4)
	/home/thangld13/go/src/siem-log-agent/agent/agent.go:33 +0x91 fp=0xc000189f18 sp=0xc000189ec8 pc=0x9f7ef1
main.main()
	/home/thangld13/go/src/siem-log-agent/main.go:105 +0x201 fp=0xc000189f98 sp=0xc000189f18 pc=0x9f8cf1
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000189fe0 sp=0xc000189f98 pc=0x43450c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000189fe8 sp=0xc000189fe0 pc=0x45e9f1

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7f3979596f08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00017a218, 0x72, 0x0, 0x0, 0xb83239)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00017a200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc00017a200, 0xb19860, 0x50, 0xc00015a870)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0000100b8, 0xc00009e000, 0x7f397e08c008, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc0000100b8, 0x412378, 0x30, 0xb19860)
	/usr/local/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc0000100b8, 0xb19860, 0xc000159080, 0xaadac0, 0x13471c0)
	/usr/local/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc000154340, 0xc606e0, 0xc0000100b8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc000154340, 0xc000154340, 0x8)
	/usr/local/go/src/net/http/server.go:2797 +0xe4
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3037
main.monitorListen(0xc0001ac2e8, 0x8, 0xc0001ac5dc, 0x4)
	/home/thangld13/go/src/siem-log-agent/main.go:91 +0xfa
created by main.main
	/home/thangld13/go/src/siem-log-agent/main.go:104 +0x1cd

rax    0x0
rbx    0x6
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7fff2540d860
rbp    0x7f397ebb7ee0
rsp    0x7fff2540d860
r8     0x0
r9     0x7fff2540d860
r10    0x8
r11    0x246
r12    0x7f397ecd6e3e
r13    0x7f397ecd6648
r14    0x12a5
r15    0x1e40630
rip    0x7f397ea6a7bb
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

How to reproduce
================

Monitor:
Using https://github.com/prometheus/prometheus to monitor events per second.
**If I don't use prometheus to monitor. My app works well on both ubuntu and debian.
If I use prometheus, it only works on ubuntu.**

Kafka input: github.com/confluentinc/confluent-kafka-go

Elasticsearch output: github.com/olivere/elastic

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.0.0-127-g5d7613
 - [ ] Apache Kafka broker version: 2.11-1.1.1
 - [ ] Client configuration: `ConfigMap{...}`
```
consumers:
  - name: SIEM
    configs:
      bootstrap.servers: myhost
      group.id: log_agent
      topic: mytopic
      auto.offset.reset: latest
      enable.auto.commit: true
```
 - [ ] Operating system: Debian GNU/Linux 9 (stretch)
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you provide the output from `ldd <your-go-app>` ? 
What librdkafka version did you build the application for (on ubuntu 18.04), and what librdkafka version is installed on the target host?

**Comment by thangld322** [comment]
Hi @edenhill ,

The output from ldd: 

```

                linux-vdso.so.1 (0x00007ffcf454c000)

                librdkafka.so.1 => /usr/local/lib/librdkafka.so.1
(0x00007f5bdb514000)

                libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007f5bdb4f3000)

                libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
(0x00007f5bdb332000)

                libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
(0x00007f5bdb1af000)

                libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2
(0x00007f5bdaf94000)

                libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
(0x00007f5bdaf03000)

                libcrypto.so.1.1 =>
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f5bdac18000)

                libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1
(0x00007f5bda9fa000)

                libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
(0x00007f5bda9f5000)

                librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
(0x00007f5bda9eb000)

                /lib64/ld-linux-x86-64.so.2 (0x00007f5bdb852000)

                libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2
(0x00007f5bda9d1000)

```

I use the librdkafka I clone from here to build my app:

```

RUN git clone https://github.com/edenhill/librdkafka.git

RUN cd librdkafka && ./configure --prefix /usr && make && make install

```

Then I copy the same librdkafka to the target host: `RUN zip -r
librdkafka.zip librdkafka`

Full docker for target host:

```

FROM debian



ARG proxy=http://192.168.5.8:3128



COPY ./agent/dispatcherv2/librdkafka.zip .



RUN env https_proxy=$proxy http_proxy=$proxy apt-get update
--allow-unauthenticated \

     && env DEBIAN_FRONTEND=noninteractive https_proxy=$proxy
http_proxy=$proxy \

        apt-get install --allow-unauthenticated -y --no-install-recommends
\

            unzip \

            zlib1g-dev \

            build-essential \

            libssl-dev \

            libsasl2-dev \

            libssl1.0.2 \

            curl \

     && apt-get clean \

     && unzip ./librdkafka.zip -d /tmp/libkafka/ \

     && /bin/bash -c 'cd /tmp/libkafka/librdkafka* && ./configure && make
&& make install' \

     && echo "include /usr/local/lib" >> /etc/ld.so.conf \

     && ldconfig \

     && rm -rf /librdkafka.zip /tmp/libkafka/ \

     && apt-get autoremove --purge -y build-essential unzip \

     && rm -rf /var/lib/apt/lists/* \

          /var/cache/debconf \

          /tmp/*



RUN rm -rf /etc/apt/sources.list.d

RUN rm -rf /etc/apt/sources.list



COPY ./sources.list /etc/apt/



ENV http_proxy=http://192.168.5.8:3128

ENV https_proxy=http://192.168.5.8:3128

ENV GIT_SSL_NO_VERIFY=1



RUN apt-get update -y

RUN apt-get install -y apt-transport-https



RUN echo "deb http://ftp.de.debian.org/debian testing main" >
/etc/apt/sources.list

RUN echo 'Acquire::https::mirror.ufs.ac.za::Verify-Peer "false";' >
/etc/apt/apt.conf

RUN apt-get update -y

RUN apt-get install -y apt-transport-https wget nano supervisor python3
python3-pip

RUN apt-get install -y python3-dev libxml2-dev libxslt1-dev zlib1g-dev

RUN pip3 install requests zipfile36 elasticsearch-curator

RUN pip3 install --proxy=http://192.168.5.8:3128 stix==1.2.0.6
taxii2-client==0.3.1 pymongo==3.6.1 configparser==3.5.0

RUN pip3 install --proxy=http://192.168.5.8:3128 Flask==1.0.2
requests==2.19.1

COPY Flask-Oauth2 /opt/siem/Flask-Oauth2

RUN cd /opt/siem/Flask-Oauth2/ && python3 setup.py install && cd -

RUN apt-get clean



ENV http_proxy=

ENV https_proxy=

```



I guess it conflicts with prometheus on debian. Because, before I use
prometheus, my app works fine on both debian and ubuntu. Now, it only works
on ubuntu.

**Comment by kingtong** [comment]
I have a similar issue since I have upgraded from Debian `stretch` to `buster`.
It only happens when running the tests with `ginkgo` and race detection enabled.

```
➜  ginkgo -race -r -focus 'Kafka'
[1562775245] Kafka Suite - 1/1 specs %2|1562775247.993|THREAD|rdkafka#consumer-1| [thrd:app]: Unable to create broker thread: Success (0)
kafka.test: rdkafka_broker.c:4773: rd_kafka_broker_add_logical: Assertion `rkb && *"failed to create broker thread"' failed.
SIGABRT: abort
PC=0x7f8149d507bb m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f8149d507bb
stack: frame={sp:0x7f8145ef2a80, fp:0x0} stack=[0x7f81456f34c8,0x7f8145ef30c8)
00007f8145ef2980:  00007f813c022eb0  e060b27929d9c500
00007f8145ef2990:  00007f813c022360  0000ffff00001fa0
00007f8145ef29a0:  00007f813c022360  00007f813c020fc8
00007f8145ef29b0:  0000000000000064  0000000000000001
00007f8145ef29c0:  0000000000000007  0000000000000070
00007f8145ef29d0:  00007f8100000007  00007f813c0008f8
00007f8145ef29e0:  000000000000005f  0000000000000090
00007f8145ef29f0:  ffffffffffffe1c8  0000000000000001
00007f8145ef2a00:  0000003100000007  0000000000000000
00007f8145ef2a10:  0000000000000000  0000006e0000005b
00007f8145ef2a20:  000000770000007c  0000000000000000
00007f8145ef2a30:  6f72622065746165  00007f813c000020
00007f8145ef2a40:  0000000000000064  0000000000000005
00007f8145ef2a50:  33373734ffffe1c8  e060b27929d9c500
00007f8145ef2a60:  00007f8145ef2aa0  000000000000007d
00007f8145ef2a70:  000000000000007d  00007f8145ef2ce0
00007f8145ef2a80: <0000000000000000  00007f813c0223d0
00007f8145ef2a90:  000000000000000b  00007f8149d914d7
00007f8145ef2aa0:  766c6f73fbad8000  00007f813c0223d0
00007f8145ef2ab0:  00007f813c022435  00007f813c0223d0
00007f8145ef2ac0:  00007f813c0223d0  00007f813c02244d
00007f8145ef2ad0:  00007f813c0224fc  00007f813c0223d0
00007f8145ef2ae0:  00007f813c0224fc  0000000000000000
00007f8145ef2af0:  0000000000000000  0000000000000000
00007f8145ef2b00:  fffffffe7fffffff  ffffffffffffffff
00007f8145ef2b10:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b20:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b30:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b40:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b50:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b60:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b70:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f8149d507bb
stack: frame={sp:0x7f8145ef2a80, fp:0x0} stack=[0x7f81456f34c8,0x7f8145ef30c8)
00007f8145ef2980:  00007f813c022eb0  e060b27929d9c500
00007f8145ef2990:  00007f813c022360  0000ffff00001fa0
00007f8145ef29a0:  00007f813c022360  00007f813c020fc8
00007f8145ef29b0:  0000000000000064  0000000000000001
00007f8145ef29c0:  0000000000000007  0000000000000070
00007f8145ef29d0:  00007f8100000007  00007f813c0008f8
00007f8145ef29e0:  000000000000005f  0000000000000090
00007f8145ef29f0:  ffffffffffffe1c8  0000000000000001
00007f8145ef2a00:  0000003100000007  0000000000000000
00007f8145ef2a10:  0000000000000000  0000006e0000005b
00007f8145ef2a20:  000000770000007c  0000000000000000
00007f8145ef2a30:  6f72622065746165  00007f813c000020
00007f8145ef2a40:  0000000000000064  0000000000000005
00007f8145ef2a50:  33373734ffffe1c8  e060b27929d9c500
00007f8145ef2a60:  00007f8145ef2aa0  000000000000007d
00007f8145ef2a70:  000000000000007d  00007f8145ef2ce0
00007f8145ef2a80: <0000000000000000  00007f813c0223d0
00007f8145ef2a90:  000000000000000b  00007f8149d914d7
00007f8145ef2aa0:  766c6f73fbad8000  00007f813c0223d0
00007f8145ef2ab0:  00007f813c022435  00007f813c0223d0
00007f8145ef2ac0:  00007f813c0223d0  00007f813c02244d
00007f8145ef2ad0:  00007f813c0224fc  00007f813c0223d0
00007f8145ef2ae0:  00007f813c0224fc  0000000000000000
00007f8145ef2af0:  0000000000000000  0000000000000000
00007f8145ef2b00:  fffffffe7fffffff  ffffffffffffffff
00007f8145ef2b10:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b20:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b30:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b40:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b50:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b60:  ffffffffffffffff  ffffffffffffffff
00007f8145ef2b70:  ffffffffffffffff  ffffffffffffffff

goroutine 37 [syscall]:
runtime.cgocall(0xb31b50, 0xc0000c6e90, 0xc0000c6e98)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/runtime/cgocall.go:128 +0x7a fp=0xc0000c6e60 sp=0xc0000c6e28 pc=0x41a06a
github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_rd_kafka_new(0x1, 0x7f813c000c60, 0x7f813c001550, 0x100, 0x0)
        _cgo_gotypes.go:1653 +0x6c fp=0xc0000c6e90 sp=0xc0000c6e60 pc=0xa3b2bc
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer.func3(0x7f813c000c60, 0x7f813c001550, 0x0)
        /home/nicolas/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.0.0/kafka/consumer.go:414 +0x83 fp=0xc0000c6ed0 sp=0xc0000c6e90 pc=0xa4e6b3
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer(0xc0000c70e0, 0x0, 0x0, 0x0)
        /home/nicolas/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.0.0/kafka/consumer.go:414 +0x39f fp=0xc0000c7008 sp=0xc0000c6ed0 pc=0xa40e9f
bitbucket.org/aerialeng/mqtt-kafka-bridge/internal/kafka_test.initConsumer(0xc4daab, 0x14, 0xc0000fd108)
        /home/nicolas/Development/repositories/mqtt-kafka-bridge/internal/kafka/kafka_test.go:23 +0x207 fp=0xc0000c7170 sp=0xc0000c7008 pc=0xb05fb7
bitbucket.org/aerialeng/mqtt-kafka-bridge/internal/kafka_test.glob..func1.1.1()
        /home/nicolas/Development/repositories/mqtt-kafka-bridge/internal/kafka/kafka_test.go:98 +0x9a fp=0xc0000c7320 sp=0xc0000c7170 pc=0xb06efa
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0000ac660, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/runner.go:113 +0xbe fp=0xc0000c7368 sp=0xc0000c7320 pc=0xab385e
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0000ac660, 0xc0000c7580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/runner.go:64 +0x108 fp=0xc0000c7510 sp=0xc0000c7368 pc=0xab3338
github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc0000aa098, 0xd265a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/setup_nodes.go:15 +0x88 fp=0xc0000c7638 sp=0xc0000c7510 pc=0xab3928
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc000222000, 0x0, 0xd265a0, 0xc0000af240)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:193 +0x2a9 fp=0xc0000c7900 sp=0xc0000c7638 pc=0xabd259
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc000222000, 0xd265a0, 0xc0000af240)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/spec/spec.go:138 +0x143 fp=0xc0000c7950 sp=0xc0000c7900 pc=0xabcd23
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0000fd180, 0xc000222000, 0x0)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:200 +0x173 fp=0xc0000c79b8 sp=0xc0000c7950 pc=0xac62b3
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0000fd180, 0x1)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:170 +0x218 fp=0xc0000c7a70 sp=0xc0000c79b8 pc=0xac5cc8
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0000fd180, 0x8)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:66 +0x141 fp=0xc0000c7ab0 sp=0xc0000c7a70 pc=0xac50b1
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0000da820, 0x7f81446931a0, 0xc0000d8b00, 0xc47d04, 0xb, 0xc00009b7d0, 0x1, 0x1, 0xd33d80, 0xc0000af240, ...)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/suite/suite.go:62 +0x6a3 fp=0xc0000c7d18 sp=0xc0000c7ab0 pc=0xac8a93
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0xd26cc0, 0xc0000d8b00, 0xc47d04, 0xb, 0xc000147710, 0x1, 0x1, 0x20)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/ginkgo_dsl.go:221 +0x33b fp=0xc0000c7ec8 sp=0xc0000c7d18 pc=0xaccccb
github.com/onsi/ginkgo.RunSpecs(0xd26cc0, 0xc0000d8b00, 0xc47d04, 0xb, 0x0)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/ginkgo_dsl.go:202 +0x9a fp=0xc0000c7f30 sp=0xc0000c7ec8 pc=0xacc95a
bitbucket.org/aerialeng/mqtt-kafka-bridge/internal/kafka_test.TestKafka(0xc0000d8b00)
        /home/nicolas/Development/repositories/mqtt-kafka-bridge/internal/kafka/kafka_test.go:19 +0x129 fp=0xc0000c7f70 sp=0xc0000c7f30 pc=0xb05d49
testing.tRunner(0xc0000d8b00, 0xc68ce0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x164 fp=0xc0000c7fd0 sp=0xc0000c7f70 pc=0x569a84
runtime.goexit()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000c7fd8 sp=0xc0000c7fd0 pc=0x475fa1
created by testing.(*T).Run
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x65b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000d8a00, 0xc46659, 0x9, 0xc68ce0, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:917 +0x693
testing.runTests.func1(0xc0000d8a00)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0xa9
testing.tRunner(0xc0000d8a00, 0xc000131db0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x164
testing.runTests(0xc0000b6c40, 0x113c560, 0x1, 0x1, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x524
testing.(*M).Run(0xc00011c500, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x2ec
main.main()
        _testmain.go:44 +0x223

goroutine 35 [syscall]:
os/signal.signal_recv(0x475fa1)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
        /home/linuxbrew/.linuxbrew/Cellar/go/1.12.6/libexec/src/os/signal/signal_unix.go:29 +0x4f

goroutine 38 [chan receive]:
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc0000fd180, 0xc00008aa20)
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:223 +0xf7
created by github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
        /home/nicolas/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/specrunner/spec_runner.go:60 +0xab

rax    0x0
rbx    0x6
rcx    0x7f8149d507bb
rdx    0x0
rdi    0x2
rsi    0x7f8145ef2a80
rbp    0x7f8149e9dee0
rsp    0x7f8145ef2a80
r8     0x0
r9     0x7f8145ef2a80
r10    0x8
r11    0x246
r12    0x7f8149fa76a0
r13    0x7f8149fa8ca0
r14    0x12a5
r15    0xb
rip    0x7f8149d507bb
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

Ginkgo ran 1 suite in 2.098365938s
Test Suite Failed
```

When I remove race condition detection tests run fine:

```
➜  ginkgo -r -focus 'Kafka' 
[1562775629] Kafka Suite - 1/1 specs • SUCCESS! 4.750881198s PASS
[1562775629] MQTT Suite - 0/1 specs S SUCCESS! 466.52µs PASS

Ginkgo ran 2 suites in 6.841945496s
Test Suite Passed
```

I'm using librdkafka 1.1.0.

**Comment by edenhill** [comment]
librdkafka needs to be able to create internal threads, I don't know what ginkgo does to prevent this but it is outside the control of the client.

**Comment by kingtong** [comment]
Ok, I'll try to poke ginkgo, thanks for the feedback.
