### ISSUE TITLE
ssl connection to broker fails : Connection disconnected immediately

### ISSUE THREAD

**Issue by pjh0915** [confluentinc/confluent-kafka-go#414]
Description
===========
I have 6 kafka brokers with ssl settings enabled, and tried to test producing message to one of them using confluent-kafka-go v1.1.0 but failed.

No topic created by the producer, and the broker's server log said the connection was disconnection immediately after the SSL handshake has completed.

There is no error from the client side.

[2019-12-27 08:24:33,739] DEBUG [SslTransportLayer channelId={broker_private_IP}:{SSL_PORT}-{client_public_IP}:48119-1 key=sun.nio.ch.SelectionKeyImpl@2a3027fa] SSL handshake completed successfully with peerHost '{client_public_IP}' peerPort 48119 peerPrincipal 'User:ANONYMOUS' cipherSuite 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384' (org.apache.kafka.common.network.SslTransportLayer)
[2019-12-27 08:24:33,739] DEBUG [SocketServer brokerId=1] Successfully authenticated with /{client_public_IP} (org.apache.kafka.common.network.Selector)
[2019-12-27 08:24:33,739] DEBUG [SocketServer brokerId=1] Connection with /{client_public_IP} disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
        at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:573)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:94)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:433)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:394)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:651)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:572)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
        at kafka.network.Processor.poll(SocketServer.scala:830)
        at kafka.network.Processor.run(SocketServer.scala:730)
        at java.lang.Thread.run(Thread.java:748)

The client host is located in the private network zone, so it connects to broker via NAT gateway.
But it seems not a problem because when I test with kafka console clients on the same host, it works. 
(kafka-console-producer.sh --broker-list '{broker public IP:SSL port}' --topic 'test_123' --producer.config '../config/client-ssl.properties')

How to reproduce
================

- The go main code that I used.

func main() {
        log.Println("creating kafka producer")

        kafkaConfig := ConfigMap{
                "bootstrap.servers":        {broker public IP:SSL port},
                "compression.codec":        "",
                "batch.num.messages":       "",
                "go.batch.producer":        true,                 
                "go.delivery.reports":      false,                  
                "security.protocol":            "ssl",
                "ssl.ca.location":          "/root/test/ssl/ca-cert",
                "ssl.certificate.location": "/root/test/ssl/client_maple_client.pem", 
                "ssl.key.location":         "/root/test/ssl/client_maple_client.key",  
                "ssl.key.password":         "abcdefgh", 
                "enable.ssl.certificate.verification":          false,
        }
        p, err := NewProducer(&kafkaConfig)
        if err != nil {
                panic(err)
        }

        defer p.Close()

        // Delivery report handler for produced messages
        go func() {
                for e := range p.Events() {
                        switch ev := e.(type) {
                        case *Message:
                                if ev.TopicPartition.Error != nil {
                                        fmt.Printf("Delivery failed: %v\n", ev.TopicPartition)
                                } else {
                                        fmt.Printf("Delivered message to %v\n", ev.TopicPartition)
                                }
                        }
                }
        }()

        // Produce messages to topic (asynchronously)
        topic := "myTopic"
        for _, word := range []string{"Welcome", "to", "the", "Confluent", "Kafka", "Golang", "client"} {
                p.Produce(&Message{
                        TopicPartition: TopicPartition{Topic: &topic, Partition: PartitionAny},
                        Value:          []byte(word),
                }, nil)
        }

        // Wait for message deliveries before shutting down
        p.Flush(15 * 1000)

}

Checklist
=========
Please provide the following information:

 - [V] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
confluent-kafka-go v1.1.0
1.1.0 (librdkafka-dev Version: 1.1.0~1confluent5.3.2-1)
 - [V] Apache Kafka broker version:
2.12 (confluent-community-2.12 Version: 5.2.3-1)
 - [V] Client configuration: `ConfigMap{...}`
listed above
 - [V] Operating system:
ubuntu-xenial-16.04-amd64
 - [V] Provide client logs (with `"debug": ".."` as necessary)
 - [V] Provide broker log excerpts
 - [V] Critical issue

**Comment by raviraj-mng** [comment]
how did you solve this. I have a similar issue

**Comment by edenhill** [comment]
Set `"debug": "security,broker"` in the ConfigMap and see if there's more information on SSL auth

**Comment by sharvil-kekre** [comment]
Was this issue ever resolved?
