### ISSUE TITLE
Produce() hangs in syscall from kafka._Cfunc_rd_kafka_topic_new

### ISSUE THREAD

**Issue by ekoutanov** [confluentinc/confluent-kafka-go#455]
Description
===========
Occurs on an application that scrapes a database table and publishes to Kafka. The design of the app is such that, upon any error, it will destroy the producer instance (and associated `.Events()` goroutine), clean up, and recreate the entire pipeline. There are several parallel producer pipelines in operation — 8 of them to be precise.

We run continuous soak testing that injects simulated faults into the application with random probabilities, forcing the app to recreate the producer instance. Occasionally, when we recreate the producer and try to publish messages on a _fresh_ producer instance, the `Produce()` method hangs.

Additional instrumentation has put in place that detects hung goroutines and dumps all stack traces. This is what we are seeing:

```
goroutine 1861 [syscall, 1 minutes]:
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka._Cfunc_rd_kafka_topic_new(0x2d812800, 0x2d51df80, 0x0, 0x0)
	_cgo_gotypes.go:2444 +0x6c
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*handle).getRkt0.func2(0xc0013fd350, 0x2d51df80, 0x2d51df80)
	/Users/emil/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.4.0/kafka/handle.go:193 +0x8a
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*handle).getRkt0(0xc0013fd350, 0xc000345f00, 0x14, 0x2d51df80, 0xc000301501, 0x0)
	/Users/emil/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.4.0/kafka/handle.go:193 +0x122
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*handle).getRkt(...)
	/Users/emil/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.4.0/kafka/handle.go:207
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*Producer).produce(0xc0013fd340, 0xc0013fd3f0, 0x0, 0x0, 0xc000222400, 0x0)
	/Users/emil/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.4.0/kafka/producer.go:156 +0xe5
gopkg.in/confluentinc/confluent-kafka-go.v1/kafka.(*Producer).Produce(0xc0013fd340, 0xc0013fd3f0, 0x0, 0xc0003305e0, 0x4c30735)
	/Users/emil/go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.4.0/kafka/producer.go:285 +0x56
gitlab.com/ekoutanov/goharvest.(*faultyProducer).Produce(0xc000222480, 0xc0013fd3f0, 0x0, 0x1, 0x2540be400)
	/Users/emil/code/goharvest/harvest.go:348 +0xeff
gitlab.com/ekoutanov/goharvest.newStage.func1(0xc0003720c0, 0xc000372120, 0xc000129770)
```
(redacted the app-level portion of the stack trace)

How to reproduce
================
The occurrence rate is low; it takes about 5 hours of continuous spinning up and down of producer clients (at a rate of ~ 1/sec) before the condition manifests.

Ideally I would provide a stripped down test case that induces this condition; I will endeavour to provide one. But even then, it would take hours of continuous cycling.

Debug logs are voluminous because there are 8 producer instances interleaved; I can't see anything untoward:
```
%7|1586758195.558|BRKMAIN|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Enter main broker thread
%7|1586758195.558|CONNECT|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Received CONNECT op
%7|1586758195.558|STATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1586758195.558|CONNECT|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1586758195.558|STATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1586758195.558|BRKMAIN|rdkafka#producer-347| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1586758195.559|CONNECT|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 56
16:09:55.559 INF Starting background delivery handler <name:harvest-#2>
%7|1586758195.559|INIT|rdkafka#producer-347| [thrd:app]: librdkafka v1.4.0 (0x10400ff) rdkafka#producer-347 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, STATIC_LINKING CC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0xe)
16:09:55.559 INF Starting background delivery handler <name:harvest-#2>
%7|1586758195.560|CONNECT|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
%7|1586758195.560|CONNECTED|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1586758195.560|FEATURE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1586758195.560|STATE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
16:09:55.560 INF Starting background delivery handler <name:harvest-#2>
%7|1586758195.561|METADATA|rdkafka#producer-340| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.561|METADATA|rdkafka#producer-340| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.561|METADATA|rdkafka#producer-340| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.561|METADATA|rdkafka#producer-340| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.561|CLUSTERID|rdkafka#producer-340| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.561|CONTROLLERID|rdkafka#producer-340| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.561|FEATURE|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.561|STATE|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.561|METADATA|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
16:09:55.564 INF Starting background delivery handler <name:harvest-#2>
%7|1586758195.561|UPDATE|rdkafka#producer-340| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.564|UPDATE|rdkafka#producer-340| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.565|CONNECT|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv6#[::1]:9092 (plaintext) with socket 57
%7|1586758195.565|FEATURE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.565|STATE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.565|METADATA|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
16:09:55.566 INF Starting background delivery handler <name:harvest-#2>
%7|1586758195.566|CONNECT|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv6#[::1]:9092
%7|1586758195.566|CONNECTED|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1586758195.566|FEATURE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1586758195.566|STATE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1586758195.568|METADATA|rdkafka#producer-341| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.568|METADATA|rdkafka#producer-341| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.568|METADATA|rdkafka#producer-341| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.568|METADATA|rdkafka#producer-341| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.568|CLUSTERID|rdkafka#producer-341| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.568|CONTROLLERID|rdkafka#producer-341| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.568|UPDATE|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.568|UPDATE|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.568|LEADER|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.568|STATE|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.568|STATE|rdkafka#producer-341| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
%7|1586758195.569|CONNECT|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 59
%7|1586758195.569|METADATA|rdkafka#producer-345| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.569|METADATA|rdkafka#producer-345| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.569|METADATA|rdkafka#producer-345| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.569|METADATA|rdkafka#producer-345| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.569|CLUSTERID|rdkafka#producer-345| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.569|CONTROLLERID|rdkafka#producer-345| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.570|FEATURE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.570|STATE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.570|METADATA|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
%7|1586758195.570|UPDATE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.570|UPDATE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.570|LEADER|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.570|STATE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.570|CONNECT|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
%7|1586758195.570|CONNECTED|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1586758195.570|FEATURE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1586758195.570|STATE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1586758195.570|STATE|rdkafka#producer-345| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
%7|1586758195.571|FEATURE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.571|METADATA|rdkafka#producer-342| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.571|METADATA|rdkafka#producer-342| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.571|CONNECT|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 52
%7|1586758195.571|STATE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.571|METADATA|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
%7|1586758195.571|METADATA|rdkafka#producer-342| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.571|METADATA|rdkafka#producer-342| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.571|CLUSTERID|rdkafka#producer-342| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.571|CONTROLLERID|rdkafka#producer-342| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.571|CONNECT|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
%7|1586758195.571|CONNECTED|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1586758195.571|FEATURE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1586758195.571|STATE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1586758195.571|UPDATE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.571|UPDATE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.571|LEADER|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.571|STATE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.571|STATE|rdkafka#producer-342| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
%7|1586758195.571|METADATA|rdkafka#producer-346| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.571|METADATA|rdkafka#producer-346| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.571|METADATA|rdkafka#producer-346| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.571|METADATA|rdkafka#producer-346| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.571|CLUSTERID|rdkafka#producer-346| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.572|CONTROLLERID|rdkafka#producer-346| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.572|UPDATE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.572|UPDATE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.572|LEADER|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.572|STATE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.572|FEATURE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.572|STATE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.572|METADATA|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
%7|1586758195.572|STATE|rdkafka#producer-346| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
%7|1586758195.572|CONNECT|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv6#[::1]:9092 (plaintext) with socket 78
%7|1586758195.572|CONNECT|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv6#[::1]:9092
%7|1586758195.572|CONNECTED|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1586758195.572|FEATURE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1586758195.572|STATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1586758195.572|METADATA|rdkafka#producer-343| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.572|METADATA|rdkafka#producer-343| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.572|METADATA|rdkafka#producer-343| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.572|METADATA|rdkafka#producer-343| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.572|CLUSTERID|rdkafka#producer-343| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.572|CONTROLLERID|rdkafka#producer-343| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.572|UPDATE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.572|UPDATE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.572|LEADER|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.572|STATE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.572|STATE|rdkafka#producer-343| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
%7|1586758195.572|FEATURE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.572|STATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.572|METADATA|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
%7|1586758195.572|CONNECT|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv6#[::1]:9092 (plaintext) with socket 55
%7|1586758195.572|CONNECT|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv6#[::1]:9092
%7|1586758195.572|CONNECTED|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1586758195.572|FEATURE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1586758195.572|STATE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1586758195.572|METADATA|rdkafka#producer-347| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.572|METADATA|rdkafka#producer-347| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.572|METADATA|rdkafka#producer-347| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.572|METADATA|rdkafka#producer-347| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.572|CLUSTERID|rdkafka#producer-347| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.572|CONTROLLERID|rdkafka#producer-347| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.572|UPDATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.572|UPDATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.572|LEADER|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.572|STATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.572|STATE|rdkafka#producer-347| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
%7|1586758195.573|FEATURE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1586758195.573|STATE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1586758195.573|METADATA|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Request metadata for brokers only: connected
%7|1586758195.573|METADATA|rdkafka#producer-344| [thrd:main]: localhost:9092/bootstrap: ===== Received metadata: connected =====
%7|1586758195.573|METADATA|rdkafka#producer-344| [thrd:main]: localhost:9092/bootstrap: ClusterId: nbbCt19KSS2wiX6zXooREg, ControllerId: 0
%7|1586758195.573|METADATA|rdkafka#producer-344| [thrd:main]: localhost:9092/bootstrap: 1 brokers, 0 topics
%7|1586758195.573|METADATA|rdkafka#producer-344| [thrd:main]: localhost:9092/bootstrap:   Broker #0/1: localhost:9092 NodeId 0
%7|1586758195.573|CLUSTERID|rdkafka#producer-344| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "nbbCt19KSS2wiX6zXooREg"
%7|1586758195.573|CONTROLLERID|rdkafka#producer-344| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1586758195.573|UPDATE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: NodeId changed from -1 to 0
%7|1586758195.573|UPDATE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Name changed from localhost:9092/bootstrap to localhost:9092/0
%7|1586758195.573|LEADER|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Mapped 0 partition(s) to broker
%7|1586758195.573|STATE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UP -> UPDATE
%7|1586758195.573|STATE|rdkafka#producer-344| [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state UPDATE -> UP
```

The broker logs are clean.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.4.0
 - [x] Apache Kafka broker version: 2.4.0
 - [x] Client configuration: `ConfigMap{...}`
```
"enable.idempotence": true,
"delivery.timeout.ms": 10000,
"debug":               "broker,topic,metadata",
```
 - [x] Operating system: macOS Mojave 10.14.6
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by ekoutanov** [comment]
As promised, here's a stripped down rig that reproduces this issue (eventually):

[https://github.com/ekoutanov/kafkaload](https://github.com/ekoutanov/kafkaload).

The only reason this is not a unit test is because it takes too long. Run instructions in the README.

**Comment by ekoutanov** [comment]
Any thoughts @edenhill ?

**Comment by edenhill** [comment]
I've looked at kafkaload and I will let it run for 5h+ later this week.
One comment though, you're not waiting for the messages to be produced before closing the producer, so most likely the message will just be dropped, you need to call Flush() prior to Close() to wait for deliveries.

**Comment by ekoutanov** [comment]
Thanks @edenhill. In our case we're happy for messages to be dropped when closing the producer. But I'll bear that in mind.

Also, interestingly, the problem only _seems_ to occur on macOS. I haven't seen it happen on Linux. But that could be just a matter of likelihood.

**Comment by edenhill** [comment]
producer.Close() will not block, no.

**Comment by ekoutanov** [comment]
@edenhill  I've raised another issue #463 of a similar nature, where the producer blocks in a syscall in `Close()`.

**Comment by ekoutanov** [comment]
Have you had any thoughts on this @edenhill ?
