### ISSUE TITLE
Transaction failure is not propagated in Go

### ISSUE THREAD

**Issue by rockwithamoon** [confluentinc/confluent-kafka-go#586]
Description
===========

An app with two transactional producers will write about a million events to Kafka before freezing in kafka._Cfunc_rd_kafka_commit_transaction. I would expect to get an error on BeginTransaction() or CommitTransaction() but these calls seem to get stuck.

librdkafka throws these errors

```
%3|1611134435.508|TXNERR|rdkafka#producer-2| [thrd:main]: Current transaction failed: Transactional API operation (commit_transaction (begin)) timed out (_TIMED_OUT)
%3|1611134436.567|TXNERR|rdkafka#producer-3| [thrd:main]: Current transaction failed: Transactional API operation (commit_transaction (begin)) timed out (_TIMED_OUT)
```

Kafka server throws these

```
Jan 20 04:17:15 localhost.localdomain kafka-server-start[15136]: [2021-01-20 04:17:15,533] INFO [TransactionCoordinator id=0] Initialized transactionalId 54785f1c-c7a2-4ce3-9305-459cb07fed53 with producerId 11032 and producer epoch 0 on partition __transaction_state-23 (kafka.coordinator.transaction.TransactionCoordinator)
Jan 20 04:20:37 localhost.localdomain kafka-server-start[15136]: [2021-01-20 04:20:37,526] INFO [TransactionCoordinator id=0] Completed rollback of ongoing transaction for transactionalId 54785f1c-c7a2-4ce3-9305-459cb07fed53 due to timeout (kafka.coordinator.transaction.TransactionCoordinator)
Jan 20 04:17:15 localhost.localdomain kafka-server-start[15136]: [2021-01-20 04:17:15,521] INFO [TransactionCoordinator id=0] Initialized transactionalId af9cc5ef-1133-4fc4-ba13-4939fa71d5c6 with producerId 11031 and producer epoch 0 on partition __transaction_state-42 (kafka.coordinator.transaction.TransactionCoordinator)
Jan 20 04:20:37 localhost.localdomain kafka-server-start[15136]: [2021-01-20 04:20:37,527] INFO [TransactionCoordinator id=0] Completed rollback of ongoing transaction for transactionalId af9cc5ef-1133-4fc4-ba13-4939fa71d5c6 due to timeout (kafka.coordinator.transaction.TransactionCoordinator)
```

This will happen after about writing 1e6 events in ~9k transactions:

```
iproc_kafka_producer_events_total{id="54785f1c-c7a2-4ce3-9305-459cb07fed53"} 1.006997e+06
iproc_kafka_producer_events_total{id="af9cc5ef-1133-4fc4-ba13-4939fa71d5c6"} 1.010225e+06
iproc_kafka_producer_messages_total{id="54785f1c-c7a2-4ce3-9305-459cb07fed53"} 8678
iproc_kafka_producer_messages_total{id="af9cc5ef-1133-4fc4-ba13-4939fa71d5c6"} 8671
```

Transaction Ids are not repeated and producers are created with the following options

```
        "bootstrap.servers":      “…”,
        "acks":                     -1,
        "enable.idempotence":     true,
        "max.in.flight":          5,
        "retries":                MaxInt32,
        "queue.buffering.max.ms": 5,
        "transactional.id":       <uuid>,
        "transaction.timeout.ms": 60000,
```

maxPollIntervalMs is 300000.

Stack dump shows this (it's stuck for 4 minutes below will stay that way for ever):

```
goroutine 148 [syscall, 4 minutes]:
github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_rd_kafka_commit_transaction(0x7f3ab4025180, 0xc00000ea5f, 0x0)
        _cgo_gotypes.go:1384 +0x4e
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).CommitTransaction.func1(0xc00052e000, 0xxxx0xc00747a600, 0xbffa1b58de544a78)
        /go/src/bitbucket.org/xxx/xxx/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:863 +0x8b
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).CommitTransaction(0xc00052e000, 0xf9d660, 0xc00747a600, 0x0, 0x0)
        /go/src/bitbucket.org/xxx/xxx/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:863 +0x45
bitbucket.org/xxx/xxx/core/kc.(*pworker).processEvents(0xc00050e190, 0xf9d6a0, 0xc01d6d9ef0, 0xc000324360, 0x9, 0xc000132c50, 0x8, 0xc03600ca00, 0x5a, 0x80, ...)
        /go/src/bitbucket.org/xxx/xxx/core/kc/producer.go:169 +0xabb
bitbucket.org/xxx/xxx/core/kc.(*pworker).mainLoop(0xc00050e190)
        /go/src/bitbucket.org/xxx/xxx/core/kc/producer.go:107 +0x778
created by bitbucket.org/xxx/xxx/core/kc.(*pworker).start
        /go/src/bitbucket.org/xxx/xxx/core/kc/producer.go:70 +0x875
```

How to reproduce
================

The code is this (events from w.kafkaProd.Events() are read on another routine):

```
        if err := w.kafkaProd.BeginTransaction(); err != nil {
                if e, ok := err.(kafka.Error); ok {
                        w.log.Printf("kafka error %s isRetriable %v requiresAbort %v isFatal %v\n",
                                e.Code().String(), e.IsRetriable(), e.TxnRequiresAbort(), e.IsFatal())
                }
                return errors.WithStack(err)
        }

        for i := range v.Values {
                if err := w.kafkaProd.Produce(&kafka.Message{
                        TopicPartition: kafka.TopicPartition{Topic: &v.Topic, Partition: v.Parts[i]},
                        Value:          v.Values[i],
                        Key:            v.Keys[i],
                }, nil); err != nil {
                        if e, ok := err.(kafka.Error); ok {
                                w.log.Printf("kafka error %s isRetriable %v requiresAbort %v isFatal %v\n",
                                        e.Code().String(), e.IsRetriable(), e.TxnRequiresAbort(), e.IsFatal())
                        }
                        if err2 := w.kafkaProd.AbortTransaction(ctx); err2 != nil {
                                return errors.WithMessage(err, err2.Error())
                        }
                        return errors.WithStack(err)
                }
        }

        if err := w.kafkaProd.CommitTransaction(ctx); err != nil {
                if e, ok := err.(kafka.Error); ok {
                        w.log.Printf("kafka error %s isRetriable %v requiresAbort %v isFatal %v\n",
                                e.Code().String(), e.IsRetriable(), e.TxnRequiresAbort(), e.IsFatal())
                }
                if err2 := w.kafkaProd.AbortTransaction(ctx); err2 != nil {
                        return errors.WithMessage(err, err2.Error())
                }
                return errors.WithStack(err)
        }
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.5.2
 - [x] Apache Kafka broker version: 2.6.1
 - [x] Client configuration: `ConfigMap{...}` (check above)
 - [x] Operating system: Linux CentOS 7
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rockwithamoon** [comment]
Please ignore / close this issue. There was a bug on the goroutine processing Events() channel where it was possible under some circumstances to exit before CommitTransaction() was completed.

**Comment by yangpan12138** [comment]
> 请忽略/关闭此问题。goroutine 处理 Events() 通道上有一个错误，在某些情况下可能会在 CommitTransaction() 完成之前退出。

能具体说明一下问题的解决方案吗？目前我也一直卡在这个问题上，还未解决，感谢
