### ISSUE TITLE
SIGSEGV producing single message

### ISSUE THREAD

**Issue by alex88** [confluentinc/confluent-kafka-go#662]
Description
===========

I'm trying to send a kafka message, I have a `kafka` package with the producer variable `var producer *kfk.Producer` .
From a `paho.mqtt.golang` message handler gorouting I call the SendMessage function below and I get this segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93eb31]

goroutine 38 [running]:
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).produce(0x0, 0xc0001e1d20, 0x0, 0xc00014eb40, 0xc0001e1cc0, 0x3)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.7.0/kafka/producer.go:156 +0x71
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).Produce(...)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.7.0/kafka/producer.go:285
gitlab.com/mqtt-bridge/kafka.SendMessage(0xe02866, 0xd, 0xea2e00, 0xc0001933b0, 0x8b, 0x946f45)
	/app/kafka/mqtt.go:26 +0x393
gitlab.com/mqtt-bridge/machine.init.1.func1(0xc0001844d0, 0xeafdb8, 0xc000192960)
	/app/machine/message_forward.go:13 +0xf6
gitlab.com/mqtt-bridge/mqtt.glob..func2(0xeb11e8, 0xc00000c3c0, 0xeafdb8, 0xc000192960)
	/app/mqtt/client.go:110 +0x133
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1.3(0xc000041f58, 0xc00000c3c0, 0xeafdb8, 0xc000192960)
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:178 +0x53
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0xc000071c20, 0xc00006f7c0, 0xc00000c3c0, 0xc000071c01)
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:180 +0x36f
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x5c
```

it seems the segafult is here https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L156 but I can't see how my topic or partition is nil?

How to reproduce
================

```go
func SendMessage(msg protoreflect.ProtoMessage) error {
	bytes, err := proto.Marshal(msg)
	if err != nil {
		log.Println("Unable to marshal protobuf message to send it to kafka")
		return err
	}

	t := "mqtt-messages"
	deliveryChan := make(chan kfk.Event)

	fmt.Printf("%+v %+v %+v\n", t, kfk.PartitionAny, bytes) # This prints the topic, -1 and the bytes message correctly

	err = producer.Produce(&kfk.Message{
		TopicPartition: kfk.TopicPartition{Topic: &t, Partition: kfk.PartitionAny},
		Value:          bytes,
	}, deliveryChan)

	if err != nil {
		return err
	}

	e := <-deliveryChan
	m := e.(*kfk.Message)

	if m.TopicPartition.Error != nil {
		log.Printf("Kafka message delivery failed: %v\n", m.TopicPartition.Error)
	} else {
		log.Printf("Kafka message delivered message to topic %s [%d] at offset %v\n", *m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
	}

	close(deliveryChan)

	return nil
}
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 17236223 1.7.0-dirty
 - [ ] Apache Kafka broker version: 2.8
 - [ ] Client configuration: `ConfigMap{...}`
 
 ```go
 	kafkaConfig := config.GetKafkaConfig()
	kfkConsumerConfig := kfk.ConfigMap{
		"bootstrap.servers": kafkaConfig.Servers,
		"sasl.mechanisms":   "PLAIN",
		"security.protocol": "SASL_SSL",
		"sasl.username":     kafkaConfig.Username,
		"sasl.password":     kafkaConfig.Password}

	kfkProducerConfig := kfkConsumerConfig
```
 
 - [ ] Operating system: linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary) haven't found how to set debug logging in the library
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by alex88** [comment]
My fault, that producer wasn't created yet
