### ISSUE TITLE
 Unknown host exception during schema registration 

### ISSUE THREAD

**Issue by Shukla-Ankur** [confluentinc/confluent-kafka-go#861]
Description
===========
1. My schema-registry application is running as docker containers in K8 pods. I am using ingress endpoint rather than a pod name.
jsonschema.NewDeserializer() is successful. However,  During schema registration, routing to master fails with error
`schema registry request failed error code: 50003: Error while forwarding register schema request to the master`

2. This does not occur if primary node is directly resolved behind ingress. Also, if I directly use pod name, error is not seen.

How to reproduce
================
1. Start schema registry in cluster mode in k8
2. Connect using ingress endpoint 
3. If application connects to secondary node first, it will try to reroute to primary with pod id. but this rerouting fails

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 v1.9.2 , no direct dependency of librdkafka
 - [x] Apache Kafka broker version:
 AWS MSK (Apache kafka v2.2.1)
 - [ ] Client configuration: `ConfigMap{...}`
```
 SchemaRegistryURL:          os.Getenv(SCHEMA_REGISTRY_URL),
BasicAuthCredentialsSource: "URL",
ConnectionTimeoutMs:        5000,
RequestTimeoutMs:           5000,
```
 - [x] Operating system:
Client-  Mac Monterey 12.5, Schema registry (K8 pods)- Debian GNU/Linux 11 (bullseye), 5.4.209-116.363.amzn2.x86_64

 - [x] Provide client logs (with `"debug": ".."` as necessary)
```
schema registry request failed error code: 50003: Error while forwarding register schema request to the master io.confluent.kafka.schemaregistry.rest.exceptions.RestRequestForwardingException: Error while forwarding register schema request to the master
io.confluent.kafka.schemaregistry.rest.exceptions.RestRequestForwardingException: Error while forwarding register schema request to the master
        at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.requestForwardingFailedException(Errors.java:149)
        at io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.register(SubjectVersionsResource.java:280)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:386)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:561)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:502)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:439)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryRequestForwardingException: Unexpected error while forwarding the registering schema request {version=0, id=-1, schemaType=JSON,references=[],schema={"$schema":"http://json-schema.org/draft/2020-12/schema","$ref":"#/$defs/User","$defs":{"Name":{"properties":{"fName":{"type":"string","default":"alex"},"sName":{"type":"string"},"tName":{"type":"string"}},"additionalProperties":false,"type":"object","required":["fName","sName"]},"User":{"properties":{"name":{"$ref":"#/$defs/Name"},"is_person":{"type":"boolean","default":true},"age":{"type":"integer","default":1},"score":{"type":"number"},"score4":{"type":"number"},"score5":{"type":"number","default":0},"score6":{"type":"number","title":"the name","description":"The name of a friend","default":0},"score7":{"type":"number","default":0},"score8":{"type":"number","default":0},"score9":{"type":"number","default":2},"score10":{"type":"number","default":0},"score11":{"type":"number","default":0},"score12":{"type":"number","default":0},"score13":{"type":"number","default":0},"score14":{"type":"number","default":0},"score15":{"type":"number","default":2}},"additionalProperties":false,"type":"object","required":["name","is_person","age","score","score8","score9","score10","score11","score12","score13","score14","score15"]}}}} to [http://sgi-svc-registry-7f8cbbfd87-gql2r:8081]
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.forwardRegisterRequestToMaster(KafkaSchemaRegistry.java:770)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.registerOrForward(KafkaSchemaRegistry.java:557)
        at io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.register(SubjectVersionsResource.java:266)
        ... 55 more
Caused by: java.net.UnknownHostException: sgi-svc-registry-7f8cbbfd87-gql2r
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:276)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:375)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:396)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:263)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:495)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.forwardRegisterRequestToMaster(KafkaSchemaRegistry.java:766)
 
```

 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
are you running a schema registry cluster? it looks like you're hitting a failover server and it wasn't able to forward to the master.

**Comment by divyasree175** [comment]
I am facing the same issue when trying to post schema from secondary schema registry cluster hosted in GCP ( Primary hosted in on-premise environment).
But GET call are working fine when hitting from secondary cluster.

**Comment by ganeshc9c** [comment]
> failover



> 




> are you running a schema registry cluster? it looks like you're hitting a failover server and it wasn't able to forward to the master.

We are not hitting the failover server, we are hitting the same server, intermittently we are facing this issue.

**Comment by ganeshc9c** [comment]
> I am facing the same issue when trying to post schema from secondary schema registry cluster hosted in GCP ( Primary hosted in on-premise environment). But GET call are working fine when hitting from secondary cluster.

Do let me know the implementation if you get any solution for this

**Comment by Shukla-Ankur** [comment]
@mhowlett yes I am running SR in cluster mode. No, both the servers (containers) are running fine. As I mentioned, if I am using ingress, route resolver can resolve to any of the running servers. In cases when it resolves to a secondary node, calls to secondary node from SR are routed to primary. This routing fails.
In my case also, I mostly saw it during initial start of client application.

**Comment by OneCricketeer** [comment]
> calls to secondary node from SR are routed to primary. This routing fails

Ingress and "route resolvers" aren't the fix for that. You need an environment variable

```
name: SCHEMA_REGISTRY_HOST_NAME
valueFrom:
  fieldRef:
    fieldPath: status.podIP
```
